/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-05-09 19:55:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dxc.RegisterDao;
import com.dxc.*;
import java.sql.*;

public final class displayMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.dxc");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.dxc.RegisterDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<!-- JavaScript Bundle with Popper -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Account Management</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap-min.css\">\r\n");
      out.write("</style>\r\n");
      out.write("<body\r\n");
      out.write("	style=\"background-image: url('https://cutewallpaper.org/21/hd-website-backgrounds/High-Resolution-Hd-Website-Background-Hd-Wallpapers-.jpg');\">\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"AdminHome.jsp\">\r\n");
      out.write("		<button type=\"submit\" class=\"btn btn-primary float-end\">Go\r\n");
      out.write("			Back Home</button>\r\n");
      out.write("	</form>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	");

try
{
       
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dxcdb","root","Mysql@2710");
        String sql = "select * from member";
        PreparedStatement stmt = con.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();
        if(rs.next()==false)
        {
            out.println("No Records in the table");
        }
        else
        {
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<table class=\"table table-striped\">\r\n");
      out.write("		<thead>\r\n");
      out.write("			<tr style=\"background-color: #77abff; font-weight: 20px\">\r\n");
      out.write("				<th scope=\"col\">User Name</th>\r\n");
      out.write("				<th scope=\"col\">Full Name</th>\r\n");
      out.write("				<th scope=\"col\">Password</th>\r\n");
      out.write("				<th scope=\"col\">Email Id</th>\r\n");
      out.write("				<th scope=\"col\">Phone No</th>\r\n");
      out.write("				<th scope=\"col\">Address</th>\r\n");
      out.write("				<th scope=\"col\">Security Qn</th>\r\n");
      out.write("				<th scope=\"col\">Opening Amt</th>\r\n");
      out.write("				<th scope=\"col\">AccountType</th>\r\n");
      out.write("				<th scope=\"col\">OpeningDate</th>\r\n");
      out.write("				<th scope=\"col\">PanCard</th>\r\n");
      out.write("				<th scope=\"col\">Delete</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</thead>\r\n");
      out.write("		");

            do
            {
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<tr scope=\"row\">\r\n");
      out.write("			<td>");
      out.print( rs.getString(1));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(2));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(3));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(4));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(5));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(6));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(7));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getInt(8));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(9));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(10));
      out.write("</td>\r\n");
      out.write("			<td>");
      out.print( rs.getString(11));
      out.write("</td>\r\n");
      out.write("			\r\n");
      out.write("			<td><a href=\"deleteMember.jsp?Email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.getEmail()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button\r\n");
      out.write("						type=\"button\" class=\"btn btn-outline-danger\">Delete</button></a></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		</tr>\r\n");
      out.write("\r\n");
      out.write("		");
}while(rs.next());
        }
       
}
catch(Exception e)
{
    System.out.println(e.getMessage());
    e.getStackTrace();
}

      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
