/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-05-09 19:03:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("  integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("    src=\"https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Account Management</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write(" \r\n");
      out.write(" <style>\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&family=Poppins:wght@400;500;600&display=swap');\r\n");
      out.write("*{\r\n");
      out.write("  margin: 0;;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  font-family: \"Poppins\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("background-image:url(\"https://cutewallpaper.org/21/hd-website-backgrounds/High-Resolution-Hd-Website-Background-Hd-Wallpapers-.jpg\");\r\n");
      out.write("\r\n");
      out.write("  height: 120vh;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".center{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  background: white;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  box-shadow: 10px 10px 15px rgba(0,0,0,0.05);\r\n");
      out.write("}\r\n");
      out.write(".center h1{\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 20px 0;\r\n");
      out.write("  border-bottom: 1px solid silver;\r\n");
      out.write("}\r\n");
      out.write(".center form{\r\n");
      out.write("  padding: 0 40px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("form .txt_field{\r\n");
      out.write("  position: relative;\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write(".txt_field input{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 0 5px;\r\n");
      out.write("  height: 40px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: none;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write(".txt_field label{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 5px;\r\n");
      out.write("  color: #adadad;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  pointer-events: none;\r\n");
      out.write("  transition: .5s;\r\n");
      out.write("}\r\n");
      out.write(".txt_field span::before{\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 40px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 0%;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background: #2691d9;\r\n");
      out.write("  transition: .5s;\r\n");
      out.write("}\r\n");
      out.write(".txt_field input:focus ~ label,\r\n");
      out.write(".txt_field input:valid ~ label{\r\n");
      out.write("  top: -5px;\r\n");
      out.write("  color: #2691d9;\r\n");
      out.write("}\r\n");
      out.write(".txt_field input:focus ~ span::before,\r\n");
      out.write(".txt_field input:valid ~ span::before{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".pass{\r\n");
      out.write("  margin: -5px 0 20px 5px;\r\n");
      out.write("  color: #a6a6a6;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".pass:hover{\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"submit\"]{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  border: 1px solid;\r\n");
      out.write("  background: #2691d9;\r\n");
      out.write("  border-radius: 25px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  color: #e9f4fb;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"submit\"]:hover{\r\n");
      out.write("  border-color: #2691d9;\r\n");
      out.write("  transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   <div class=\"center\">\r\n");
      out.write("      <h1>Customer Login</h1>\r\n");
      out.write("      <form action=\"memberHome.jsp\" method=\"post\">\r\n");
      out.write("        <div class=\"txt_field\">\r\n");
      out.write("          <input type=\"email\" name=\"Email\" required>\r\n");
      out.write("          <span></span>\r\n");
      out.write("          <label for=\"Email\">Email</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"txt_field\">\r\n");
      out.write("          <input type=\"password\" name=\"Account_Password\" required>\r\n");
      out.write("          <span></span>\r\n");
      out.write("          <label for=\"Account_Password\">Password</label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <input type=\"submit\" value=\"Login\">\r\n");
      out.write("       <br><br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $(\"#loginForm\").validate({\r\n");
      out.write("            rules: {\r\n");
      out.write("                Email: {\r\n");
      out.write("                    required: true,\r\n");
      out.write("                    Email: true\r\n");
      out.write("                },\r\n");
      out.write("         \r\n");
      out.write("                Account_Password: \"required\",\r\n");
      out.write("            },\r\n");
      out.write("             \r\n");
      out.write("            messages: {\r\n");
      out.write("                Email: {\r\n");
      out.write("                    required: \"Please enter email\",\r\n");
      out.write("                    Email: \"Please enter a valid email address\"\r\n");
      out.write("                },\r\n");
      out.write("                 \r\n");
      out.write("                Account_Password: \"Please enter password\"\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write(" \r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
